version: '3.3'

networks:
  fonos:

services:

  oauth2:
    image: fonoster/oauth2:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth2.entrypoints=websecure"
      - "traefik.http.services.oauth2.loadbalancer.server.port=3000"
      - "traefik.http.routers.oauth2.rule=PathPrefix(`/auth/github/callback`)"
    environment: 
      - CLIENT_ID
      - CLIENT_SECRET
      - CALLBACK_URL
      - ENDPOINT
      - PAGE_TITLE
      - PAGE_MESSAGE
      - ACCESS_LIST
    volumes:
      - ${CONFIG}/config:/home/fonos/.fonos/config
    networks:
      fonos:
